Solution_E.Shop.by/E.Shop/Areas/User/Controllers/ModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using E.Shop.Models;
using E.Shop.Store.Data;
using E.Shop.Store.Data.Models;

namespace E.Shop.Areas.User.Controllers
{
    public class ModelsController : Controller
    {
       
        private IGenericRepository<Model> models;

        public ModelsController(IGenericRepository<Model> models)
        {
            this.models = models;
        }

        // GET: User/Models/Index
        //   [Authorize(Roles = "User")]
        public async Task<ActionResult> Index(int id)
        {
            var users = Request.IsAuthenticated.ToString();
            ModelDetailsView modelDetailsView = Parse.ToModelDetailsView(await models.FindByIdAsync(id));
            return View(modelDetailsView);
        }
   }
}

Solution_E.Shop.by/E.Shop/Controllers/ExRatesController.cs
using E.Shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace E.Shop.Controllers
{
    public class ExRatesController : Controller
    {
        // GET: ExRates
        [OutputCache(Duration = 2*3600, VaryByParam = "*")]
        [ChildActionOnly]
        public ActionResult GetExRates()
        {
            var exRateClient = new ExRates.ExRatesSoapClient();
            var exRatesData = exRateClient.ExRatesDaily(DateTime.Now);
            ViewBag.UpdateDate = DateTime.Now;
            var selectedRates = exRatesData.Tables[0].Select(
                "Cur_Abbreviation = 'EUR' OR Cur_Abbreviation='RUB' OR Cur_Abbreviation='USD'").Select(row =>
                    new ExRateItem()
                    {
                        Exchange = row["Cur_Abbreviation"].ToString(),
                        Rate = (decimal) row["Cur_OfficialRate"]
                    }).ToArray();

            /* Использование как тип результата PartialView предотвращает вставку в HTML отклик общей части страницы: 
             * тегов <html><head>..</head><body>…</body>. При использовании PartialView будет выводиться только та HTML разметка, 
             * которая непосредственно генерируется в файле GetExRates.cshtml*/
            return PartialView("GetExRates", selectedRates);
        }

        [OutputCache(Duration = 2*3600, VaryByParam = "*")]
        public ActionResult GetExRatesAjax()
        {
            return GetExRates();
        }
    }
}

Solution_E.Shop.by/E.Shop/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>E.Shop Store</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/Content/jquery")
</head>
<body>
    <table align="center" width="1024" cellspacing="8">
        <tr>
            <td colspan="3">
                <img src="@Url.Content("~/Content/Images/BlackLogo.png")" alt="no logo" />
            </td>
        </tr>
        <tr>
            <td colspan="3" id="menuPanel">
                <table width="100%" class="title" cellspacing="0" cellpadding="0" border="0" style="border-collapse: collapse;">
                    <tr>
                        <td width="80%">
                            @Html.MvcSiteMap().SiteMapPath()
                        </td>
                        <td style="background-color: whitesmoke">@Html.Partial("_LoginPartial")</td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td width="20%">
                <div id="leftPanel">
                    @if (IsSectionDefined("leftPanel"))
                    {
                        @RenderSection("leftPanel")
                    }
                    else
                    {
                        @Html.MvcSiteMap().Menu()
                    }

                </div>
            </td>
            <td>
                <div id="contentPanel"> @RenderBody()</div>
            </td>
            <td width="15%">
                <!-- Partial view GetExRates loading in JQuery and AJAX : return html-->
                <div id="exchangeRates" data-url="@Url.Action("GetExRatesAjax", "ExRates")"></div>
                <script type="text/javascript">
                    $(document).ready(function () {
                        var url = $("#exchangeRates").data('url');
                        $("#exchangeRates").load(url);
                    });
                </script>
                <div id="searchPanel">
                </div>
                <div id="rightPanel">
                    @RenderSection("rightPanel", false)
                </div>
            </td>
        </tr>
        <tr>
            <td colspan="3" align="center">
                <span class="footer">2017 - Aspx E.Shop application</span>
            </td>
        </tr>
    </table>
</body>
</html>

Solution_E.Shop.by/E.Shop/Views/Shared/_ModelViewData.cshtml
@using E.Shop.App_Code
@using PagedList.Mvc;
@model PagedList.IPagedList<E.Shop.Models.ModelView>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
<div class="small" style="text-align: right">
    Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", @HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString(), new {page}),
    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
    {
        LinkToFirstPageFormat = "<<",
        LinkToPreviousPageFormat = "Назад",
        LinkToNextPageFormat = "Вперед",
        LinkToLastPageFormat = ">>"
    }

      , new AjaxOptions() { HttpMethod = "GET", UpdateTargetId = "results", LoadingElementId = "loading", }))
</div>

    <div style="overflow: hidden">
        <ul class="model_list">
            @foreach (var value in Model)
            {
                <li>
                    <div style="width: 140px; height: 180px; text-align: center; border: solid 1px #d8bfd8; padding: 5px;">
                        <div style="height: 100px">
                            <a href="@GetImgUrl(value.ModelId)">
                                <img class="img.center" src="@Url.Content(value.imgUrl)" />
                            </a>
                        </div>
                        <div class="title" style="font-size: 10px; text-align: left; height: 30px">
                            @Html.ShortString(@value.Title, 25)
                        </div>
                        <div>@($"$ {value.Price:N2}")</div>
                    </div>
                </li>
            }
        </ul>
    </div>



@helper GetImgUrl(int modelId)
{
if (Request.IsAuthenticated)
{
    var areaName = User.IsInRole("Admin") ? "Admin" : "User";
    @Url.Action("Index", "Models", new { area = areaName, id = modelId })
}
else
{  @Url.Action("Login", "Account")}
}